/**
 * Reading, creating and writing `annotation.project.json`.
 *
 * Keeps three files in step, because two of them are what makes a project usable
 * outside this application:
 *   annotation.project.json  the app's own settings
 *   classes.txt              plain names, one per line - half the YOLO ecosystem reads it
 *   data.yaml                the ultralytics dataset descriptor
 */

import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import { basename, join } from 'node:path'
import { ERROR_CODES } from '@shared/ipc'
import {
  PROJECT_FILENAME,
  STATE_DIRNAME,
  classNames,
  defaultProject,
  projectSchema,
  type Project,
  type ProjectFile
} from '@shared/project'
import { ServiceError } from './errors'
import { safeJoin } from './paths'

export async function openProject(root: string): Promise<Project> {
  const file = join(root, PROJECT_FILENAME)
  let raw: string
  try {
    raw = await readFile(file, 'utf-8')
  } catch {
    throw new ServiceError(ERROR_CODES.projectNotFound, 'no project file here', file)
  }

  const parsed = projectSchema.safeParse(JSON.parse(raw))
  if (!parsed.success) {
    throw new ServiceError(
      ERROR_CODES.projectInvalid,
      'project file could not be read',
      parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ')
    )
  }
  return { ...parsed.data, root }
}

export async function createProject(input: {
  root: string
  name?: string
  task?: ProjectFile['task']
}): Promise<Project> {
  const { root } = input

  // Idempotent: opening an existing project folder must never overwrite it.
  try {
    return await openProject(root)
  } catch (error) {
    if (!(error instanceof ServiceError) || error.code !== ERROR_CODES.projectNotFound) throw error
  }

  const project: Project = {
    ...defaultProject(input.name || basename(root)),
    task: input.task ?? 'detect',
    root
  }
  await mkdir(safeJoin(root, project.paths.input), { recursive: true })
  await mkdir(safeJoin(root, project.paths.images), { recursive: true })
  await mkdir(safeJoin(root, project.paths.labels), { recursive: true })
  await mkdir(safeJoin(root, project.paths.recycle), { recursive: true })
  await mkdir(safeJoin(root, STATE_DIRNAME), { recursive: true })
  await writeFile(safeJoin(root, STATE_DIRNAME, '.gitignore'), '*\n', 'utf-8')
  await saveProject(project)
  return project
}

/**
 * Make sure the folders the app writes into exist.
 *
 * Called when a project is opened, not on every request: a project created before the
 * inbox existed has no `input/`, and the annotate screen would otherwise send people to
 * a folder that is not there.
 */
export async function ensureLayout(project: Project): Promise<Project> {
  for (const dir of [
    project.paths.input,
    project.paths.images,
    project.paths.labels,
    project.paths.recycle
  ]) {
    await mkdir(safeJoin(project.root, dir), { recursive: true })
  }
  return project
}

export async function saveProject(project: Project): Promise<Project> {
  const { root, ...file } = project
  const target = join(root, PROJECT_FILENAME)
  const temp = `${target}.tmp`
  await mkdir(root, { recursive: true })
  await writeFile(temp, JSON.stringify(file, null, 2) + '\n', 'utf-8')
  await rename(temp, target)
  await writeClassesTxt(project)
  return project
}

export async function writeClassesTxt(project: Project): Promise<string> {
  const target = safeJoin(project.root, 'classes.txt')
  await writeFile(target, classNames(project.classes).join('\n') + '\n', 'utf-8')
  return target
}

/**
 * Write `data.yaml` by hand rather than pulling in a YAML library: the file is a
 * handful of lines and this keeps the dependency list honest.
 */
export async function writeDataYaml(project: Project, splitsRoot?: string): Promise<string> {
  const target = safeJoin(project.root, 'data.yaml')
  const base = splitsRoot ?? safeJoin(project.root, project.paths.output)
  const names = classNames(project.classes)
  const lines = [
    '# Generated by Annotation Helper. Safe to edit; regenerating overwrites it.',
    // Forward slashes: a Windows backslash in YAML is an escape sequence.
    `path: ${base.replace(/\\/g, '/')}`,
    'train: train/images',
    'val: val/images',
    ...(project.split.test > 0 ? ['test: test/images'] : []),
    `nc: ${names.length}`,
    'names:',
    ...names.map((name, i) => `  ${i}: ${name}`)
  ]
  await writeFile(target, lines.join('\n') + '\n', 'utf-8')
  return target
}
